# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/PropTextInspector.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PropTextInspector(object):
    def setupUi(self, PropTextInspector):
        PropTextInspector.setObjectName("PropTextInspector")
        PropTextInspector.resize(221, 309)
        self.verticalLayout = QtWidgets.QVBoxLayout(PropTextInspector)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cbShowName = QtWidgets.QCheckBox(PropTextInspector)
        self.cbShowName.setEnabled(False)
        self.cbShowName.setObjectName("cbShowName")
        self.gridLayout_2.addWidget(self.cbShowName, 3, 0, 1, 2)
        self.leValue = QtWidgets.QLineEdit(PropTextInspector)
        self.leValue.setObjectName("leValue")
        self.gridLayout_2.addWidget(self.leValue, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(PropTextInspector)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.cbProp = QtWidgets.QComboBox(PropTextInspector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbProp.sizePolicy().hasHeightForWidth())
        self.cbProp.setSizePolicy(sizePolicy)
        self.cbProp.setEditable(True)
        self.cbProp.setObjectName("cbProp")
        self.gridLayout_2.addWidget(self.cbProp, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(PropTextInspector)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.cbVis = QtWidgets.QCheckBox(PropTextInspector)
        self.cbVis.setObjectName("cbVis")
        self.gridLayout_2.addWidget(self.cbVis, 2, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.fontFace = QtWidgets.QFontComboBox(PropTextInspector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontFace.sizePolicy().hasHeightForWidth())
        self.fontFace.setSizePolicy(sizePolicy)
        self.fontFace.setMinimumSize(QtCore.QSize(100, 0))
        self.fontFace.setMaxVisibleItems(99)
        self.fontFace.setObjectName("fontFace")
        self.horizontalLayout_3.addWidget(self.fontFace)
        self.fontSize = QtWidgets.QComboBox(PropTextInspector)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fontSize.sizePolicy().hasHeightForWidth())
        self.fontSize.setSizePolicy(sizePolicy)
        self.fontSize.setEditable(True)
        self.fontSize.setObjectName("fontSize")
        self.horizontalLayout_3.addWidget(self.fontSize)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(PropTextInspector)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSpacing(4)
        self.gridLayout.setObjectName("gridLayout")
        self.btnMidCtr = QtWidgets.QPushButton(PropTextInspector)
        self.btnMidCtr.setMaximumSize(QtCore.QSize(15, 15))
        self.btnMidCtr.setText("")
        self.btnMidCtr.setCheckable(True)
        self.btnMidCtr.setChecked(True)
        self.btnMidCtr.setObjectName("btnMidCtr")
        self.alignGroup = QtWidgets.QButtonGroup(PropTextInspector)
        self.alignGroup.setObjectName("alignGroup")
        self.alignGroup.addButton(self.btnMidCtr)
        self.gridLayout.addWidget(self.btnMidCtr, 2, 3, 1, 1)
        self.btnMidLeft = QtWidgets.QPushButton(PropTextInspector)
        self.btnMidLeft.setMaximumSize(QtCore.QSize(15, 15))
        self.btnMidLeft.setText("")
        self.btnMidLeft.setCheckable(True)
        self.btnMidLeft.setObjectName("btnMidLeft")
        self.alignGroup.addButton(self.btnMidLeft)
        self.gridLayout.addWidget(self.btnMidLeft, 2, 2, 1, 1)
        self.btnTopLeft = QtWidgets.QPushButton(PropTextInspector)
        self.btnTopLeft.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTopLeft.sizePolicy().hasHeightForWidth())
        self.btnTopLeft.setSizePolicy(sizePolicy)
        self.btnTopLeft.setMaximumSize(QtCore.QSize(15, 15))
        self.btnTopLeft.setText("")
        self.btnTopLeft.setCheckable(True)
        self.btnTopLeft.setObjectName("btnTopLeft")
        self.alignGroup.addButton(self.btnTopLeft)
        self.gridLayout.addWidget(self.btnTopLeft, 1, 2, 1, 1)
        self.btnTopRight = QtWidgets.QPushButton(PropTextInspector)
        self.btnTopRight.setMaximumSize(QtCore.QSize(15, 15))
        self.btnTopRight.setText("")
        self.btnTopRight.setCheckable(True)
        self.btnTopRight.setObjectName("btnTopRight")
        self.alignGroup.addButton(self.btnTopRight)
        self.gridLayout.addWidget(self.btnTopRight, 1, 4, 1, 1)
        self.btnTopCtr = QtWidgets.QPushButton(PropTextInspector)
        self.btnTopCtr.setMaximumSize(QtCore.QSize(15, 15))
        self.btnTopCtr.setText("")
        self.btnTopCtr.setCheckable(True)
        self.btnTopCtr.setObjectName("btnTopCtr")
        self.alignGroup.addButton(self.btnTopCtr)
        self.gridLayout.addWidget(self.btnTopCtr, 1, 3, 1, 1)
        self.btnBotCtr = QtWidgets.QPushButton(PropTextInspector)
        self.btnBotCtr.setMaximumSize(QtCore.QSize(15, 15))
        self.btnBotCtr.setText("")
        self.btnBotCtr.setCheckable(True)
        self.btnBotCtr.setObjectName("btnBotCtr")
        self.alignGroup.addButton(self.btnBotCtr)
        self.gridLayout.addWidget(self.btnBotCtr, 3, 3, 1, 1)
        self.btnMidRight = QtWidgets.QPushButton(PropTextInspector)
        self.btnMidRight.setMaximumSize(QtCore.QSize(15, 15))
        self.btnMidRight.setText("")
        self.btnMidRight.setCheckable(True)
        self.btnMidRight.setObjectName("btnMidRight")
        self.alignGroup.addButton(self.btnMidRight)
        self.gridLayout.addWidget(self.btnMidRight, 2, 4, 1, 1)
        self.btnBotLeft = QtWidgets.QPushButton(PropTextInspector)
        self.btnBotLeft.setMaximumSize(QtCore.QSize(15, 15))
        self.btnBotLeft.setText("")
        self.btnBotLeft.setCheckable(True)
        self.btnBotLeft.setObjectName("btnBotLeft")
        self.alignGroup.addButton(self.btnBotLeft)
        self.gridLayout.addWidget(self.btnBotLeft, 3, 2, 1, 1)
        self.btnBotRight = QtWidgets.QPushButton(PropTextInspector)
        self.btnBotRight.setMaximumSize(QtCore.QSize(15, 15))
        self.btnBotRight.setText("")
        self.btnBotRight.setCheckable(True)
        self.btnBotRight.setObjectName("btnBotRight")
        self.alignGroup.addButton(self.btnBotRight)
        self.gridLayout.addWidget(self.btnBotRight, 3, 4, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(PropTextInspector)
        self.cbVis.toggled['bool'].connect(self.cbShowName.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(PropTextInspector)

    def retranslateUi(self, PropTextInspector):
        _translate = QtCore.QCoreApplication.translate
        PropTextInspector.setWindowTitle(_translate("PropTextInspector", "Form"))
        self.cbShowName.setText(_translate("PropTextInspector", "Show attribute name"))
        self.label_3.setText(_translate("PropTextInspector", "Value"))
        self.label.setText(_translate("PropTextInspector", "Attribute"))
        self.cbVis.setText(_translate("PropTextInspector", "Visible"))
        self.label_2.setText(_translate("PropTextInspector", "Alignment"))

